// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz0UXCOTn6iSjWxx_ZixffLKvEPohhQzc',
    appId: '1:5585638195:web:da151736c835b17d19a446',
    messagingSenderId: '5585638195',
    projectId: 'aaabss',
    authDomain: 'aaabss.firebaseapp.com',
    storageBucket: 'aaabss.appspot.com',
    measurementId: 'G-16Q31P962G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQqtBafyfKHmSfbtecXgMHpopg-rS0bAM',
    appId: '1:5585638195:android:b18a0423d6e3fc9e19a446',
    messagingSenderId: '5585638195',
    projectId: 'aaabss',
    storageBucket: 'aaabss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmz-hBV1is-j9d6EujgJibFPueirgqDMA',
    appId: '1:5585638195:ios:9a84f484055f18de19a446',
    messagingSenderId: '5585638195',
    projectId: 'aaabss',
    storageBucket: 'aaabss.appspot.com',
    iosBundleId: 'com.example.provider.provider',
  );
}
